name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create zip
        run: |
          cd custom_components/aqara_doorbell
          zip -r ../../aqara_doorbell.zip . \

      - name: Upload release asset
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release upload "${{ github.event.release.tag_name }}" aqara_doorbell.zip --clobber